version: '3'

services:
  db:
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    restart: always
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile.web
    command: /start.sh && python manage.py collectstatic --noinput
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      IN_DOCKER: 1
      ILIAS_DB_NAME: "${ILIAS_DB_NAME}"
      ILIAS_DB_USER: "${ILIAS_DB_USER}"
      ILIAS_DB_PASS: "${ILIAS_DB_PASS}"
      ILIAS_DB_HOST: "${ILIAS_DB_HOST}"
      ILIAS_DB_PORT: "${ILIAS_DB_PORT}"
      EMAIL_HOST: "${EMAIL_HOST}"
      EMAIL_PORT: "${EMAIL_PORT}"
      EMAIL_HOST_USER: "${EMAIL_HOST_USER}"
      EMAIL_HOST_PASSWORD: "${EMAIL_HOST_PASSWORD}"
      JWT_ALGORITHM: "${JWT_ALGORITHM}"
      JWT_USER_SECRET: "${JWT_USER_SECRET}"
      JWT_ADMIN_SECRET: "${JWT_ADMIN_SECRET}"
      DJANGO_ALLOWED_HOSTS: "${DJANGO_ALLOWED_HOSTS}"
      DEBUG: 1
    volumes:
      - .:/app
    links:
      - db
    depends_on:
      - db
    ports:
      - "8000:8000"
