version: '3'

services:
  db:
    environment:
      POSTGRES_DB: db_app
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pass
    restart: always
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile-dev
    command: python3 manage.py runserver 0.0.0.0:8000
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      IN_DOCKER: 1
      ILIAS_DB_NAME: "${ILIAS_DB_NAME}"
      ILIAS_DB_USER: "${ILIAS_DB_USER}"
      ILIAS_DB_PASS: "${ILIAS_DB_PASS}"
      ILIAS_DB_HOST: "${ILIAS_DB_HOST}"
      ILIAS_DB_PORT: "${ILIAS_DB_PORT}"
      EMAIL_HOST: "${EMAIL_HOST}"
      EMAIL_PORT: "${EMAIL_PORT}"
      EMAIL_HOST_USER: "${EMAIL_HOST_USER}"
      EMAIL_HOST_PASSWORD: "${EMAIL_HOST_PASSWORD}"
    volumes:
      - .:/app
    links:
      - db
    ports:
      - "8000:8000"
